[book]
language = "en"
authors = ["FIT3170-FY-Project-7"]
multilingual = false
src = "src"
title = "RABIT Documentation"

[output.html]
git-repository-url = "https://github.com/FIT3170-FY-Project-7/RABIT-DOCS"
git-repository-icon = "fa-github"

[output.html.playground]
editable = true
