[book]
language = "en"
authors = ["FIT3170-FY-Project-7"]
multilingual = false
src = "src"
title = "RABIT Documentation"

[output.html]
# TODO: edit the url once repo is transferred to rabit org
git-repository-url = "https://github.com/megascrapper/rabit-docs"
git-repository-icon = "fa-github"

[output.html.playground]
editable = true
